### PR TITLE
fix `positionOffset` for openPMD IO

### LINKED ISSUE #4319: positionOffset (still) wrong in openPMD output
With the bug fix #4283 the discrepancy between the mesh positionOffset and the particle positionOffset was fixed. Now both should agree. 

This week @JessicaTiebel had a look at the *default* LWFA example and observed discrepancies between the mesh and the particle positions. The PIConGPU version used was `0.7.0-dev` with `commit 5788150dbba29288be24c4a886e51f279fdde1d0` from Oct 5 2022 and thus should include fix #4283. 

A detailed analysis of the evolution between mesh position (mesh's `positionOffset` and mesh's `positionOffset` + mesh's length; in y) and the maximum and minimum particle `positionOffset` show that the particle `positionOffsets` offsets from the meshes range as soon as the moving window starts. 

The following plot shows in the green the range of the mesh (`E_x`) and in gray are minimal and maximal position in cells. 
In red the difference between minimal and maximal particle position is plotted with the dashed red line marking the mesh's hight in y (const. = 768 cells). 
Obviously it is not just a simple offset error since the range of particle positions changes constantly (and not only in the beginning, when we have no particles in the first few cells)

grafik

The python code to generate the plot is:
```python
import numpy as np
import openpmd_api as io
import matplotlib.pyplot as plt

series = io.Series("__path_to_sim__/simOutput/openPMD/simData_%T.bp",
                  io.Access.read_only)

# arrays for data
iterations_list = []
min_max_pos = np.zeros((len(series.iterations), 2)) # particles min max position
mesh_pos = np.zeros((len(series.iterations), 2)) # mesh globalOffset and mesh length (should be const.) 

# read from all iterations
for index_tmp, tmp in enumerate(series.iterations):
    iterations_list.append(tmp)
    iteration = series.iterations[tmp]
    e_h = iteration.particles['e']
    posOffset = e_h['positionOffset']['y'][:]
    series.flush()
    min_max_pos[index_tmp, :] = np.amin(posOffset), np.amax(posOffset) # min max particle position
    
    mesh_pos[index_tmp, 0] = iteration.meshes['E'].get_attribute('gridGlobalOffset')[1] # 1 = y offset
    mesh_pos[index_tmp, 1] = iteration.meshes['E']['x'].shape[1] # 1 = y mesh length
    series.flush() # not realy needed 

# plot results
plt.figure(facecolor="w")

# mesh range
plt.fill_betweenx(iterations_list, x1=mesh_pos[:, 0], x2=mesh_pos[:, 0] + mesh_pos[:, 1], color="green", alpha=0.5)

# particle min max position
plt.plot(min_max_pos[:, 0], iterations_list, color="gray")
plt.plot(min_max_pos[:, 1], iterations_list, color="gray")

# difference between min max and max mesh range
plt.plot(min_max_pos[:, 1] - min_max_pos[:, 0], iterations_list, color="red")
plt.plot(mesh_pos[:, 1], iterations_list, "--", color="red")

plt.xlim(0, 5000)
plt.ylim(0, 5000)
plt.xlabel("position [cells]", fontsize=18)
plt.xticks(fontsize=14)
plt.ylabel("time step", fontsize=18)
plt.yticks(fontsize=14)

plt.tight_layout()
plt.show()
```

### PR DESCRIPTION
**Pull request by psychocoderHPC**
fix #4319

Fix that the wrong window offset was used for restarting and wrong offsets where used for writing.

This commit is a breaking change for the IO format, therefore the major IO version is increased to 2.0.

### CODE REVIEW

**Comment by PrometheusPi** [comment]
I will test this today.

File: include/picongpu/plugins/openPMD/Json.cpp [hunk 1]
```diff
@@ -298,7 +298,7 @@ The key 'select' must point to either a single string or an array of strings.)EN
             auto& hdf5Dataset = config["hdf5"]["dataset"];
             if(!hdf5Dataset.contains("chunks"))
             {
-                hdf5Dataset["chunks"] = "none";
+                // hdf5Dataset["chunks"] = "none";
```
Comment (PrometheusPi) [inline include/picongpu/plugins/openPMD/Json.cpp]: What does this line do? / Why was this commented?

**Review by PrometheusPi — DISMISSED** [review]
Code syntax wise, this PR request looks good to me. 
Please wait till run time tests have verified the correctness. 

@psychocoderHPC Since this is now different than the change suggested in the original issue, and most of it looks like "just" renaming, could you please write in 2-3 sentences what you changed and what caused the error so that it is documented with this PR?

File: include/picongpu/plugins/openPMD/Json.cpp (hunk 1 above)
Comment (psychocoderHPC) [reply include/picongpu/plugins/openPMD/Json.cpp]: This should be not part of the PR. with the HDF5 version on our dev system this change is required else HDF5 is deadlocking. I will remove it .

Comment (psychocoderHPC) [reply include/picongpu/plugins/openPMD/Json.cpp]: fixed

**Comment by PrometheusPi** [comment]
The fix seems to be much better than the current version, **but** there is still a different speed at which particles vs. grids propagate.

grafik

This will result in an ever increasing shift between cell position and particles position in that cell.

**Comment by PrometheusPi** [comment]
I checked which of the slops (green: mesh, gray: particles) agree with the speed of light.
It looks like particles move now correctly **but** mashes move slower tan the speed of light (or I am misinterpreting the offsets) 
In blue I added a line that shows how a speed of light slope should look like. 
The gray line (particles) and the blue (speed of light) have the same slope. 
The green (mesh) slope is lower and thus its velocity in this (y-t) plot seems to be faster than the speed of light. 

grafik


From the part this PR fixes everything looks correct.

**Comment by PrometheusPi** [comment]
To add the blue line to the analysis, I plotted:
```python
DELTA_T_SI = 1.39e-16
CELL_HEIGHT_SI = 0.4430e-7
tmp_y = np.linspace(0, 4000, 1000)
plt.plot(tmp_y*DELTA_T_SI * const.c / CELL_HEIGHT_SI, tmp_y-200, color="C0", alpha=1.0)
```
together with the [other code from the original issue](https://github.com/ComputationalRadiationPhysics/picongpu/issues/4319#issue-1407944688).

**Comment by PrometheusPi** [comment]
The error I have seen is on my side.
The openPMD standard leaves the freedom of having two different length units for `meshGlobalOffset` and `positionGlobalOffset` (the mesh one differs from the regular `unitLength` in PIConGPU) and additionally scaling the cells.
If corrected for this difference, everything agrees. 
(the correct conversion is quite complicated and follows the comment "`# this is really complicated stuff`" in the code snippet below)

grafik


Code to generate this plot:
```python
 # load data 
series = io.Series("./test_picongpu/setup/LWFA/runs/002_LWFA_pr4339/simOutput/openPMD/simData_%T.bp",
                  io.Access.read_only)

# arrays for data
iterations_list = []
min_max_pos = np.zeros((len(series.iterations), 2)) # particles min max position
mesh_pos = np.zeros((len(series.iterations), 2)) # mesh globalOffset and mesh length (should be const.) 

# read from all iterations
for index_tmp, tmp in enumerate(series.iterations):
    iterations_list.append(tmp)
    iteration = series.iterations[tmp]
    e_h = iteration.particles['e']
    posOffset = e_h['positionOffset']['y'][:]
    #print(e_h['positionOffset']['y'].get_attributes())
    posOffset_SI = e_h['positionOffset']['y'].unit_SI
    series.flush()
    posOffset = posOffset * posOffset_SI # convert to unit SI
    min_max_pos[index_tmp, :] = np.amin(posOffset), np.amax(posOffset) # min max particle position in [m]
    
    # this is really complicated stuff
    tmp_mesh_1 = iteration.meshes['E'].get_attribute('gridGlobalOffset')[1] # 1 = y offset
    tmp_mesh_2 = iteration.meshes['E'].get_attribute('gridSpacing')[1] # spacing of grid
    tmp_mesh_3 = iteration.meshes['E']['x'].shape[1] # 1 = y mesh length    
    tmp_mesh_unitSI = iteration.meshes['E'].get_attribute('gridUnitSI') # SI length unit of Grid (!not equal lengthUnitSI)
    series.flush() # not realy needed 
    mesh_pos[index_tmp, 0] = tmp_mesh_1 * tmp_mesh_unitSI 
    mesh_pos[index_tmp, 1] = tmp_mesh_2 * tmp_mesh_3 * tmp_mesh_unitSI
    series.flush() # not realy needed 
    

# plot results
plt.figure(facecolor="w")

# mesh range
plt.fill_betweenx(iterations_list, x1=(mesh_pos[:, 0])/CELL_HEIGHT_SI, x2=(mesh_pos[:, 0] + mesh_pos[:, 1])/CELL_HEIGHT_SI, color="green", alpha=0.5)

# particle min max position
plt.plot(min_max_pos[:, 0]/CELL_HEIGHT_SI, iterations_list, color="gray")
plt.plot(min_max_pos[:, 1]/CELL_HEIGHT_SI, iterations_list, color="gray")



DELTA_T_SI = 1.39e-16
CELL_HEIGHT_SI = 0.4430e-7
tmp_y = np.linspace(0, 4000, 1000)
plt.plot(tmp_y*DELTA_T_SI * const.c /CELL_HEIGHT_SI, tmp_y, color="C0", alpha=1.0)

plt.xlim(0, 4000)
plt.ylim(0, 4000)
plt.xlabel("position [cells]", fontsize=18)
plt.xticks(fontsize=14)
plt.ylabel("time step", fontsize=18)
plt.yticks(fontsize=14)

plt.tight_layout()
plt.show()
```

**Comment by PrometheusPi** [comment]
@psychocoderHPC What did your last push change?

**Review by PrometheusPi — APPROVED** [review]

**Comment by psychocoderHPC** [comment]
> @psychocoderHPC What did your last push change?

It was removing the change in the JSON HDF5 config. It was a change that should not be part of the PR. All other logic/offsets, .. is equal to what it was yesterday.

**Comment by psychocoderHPC** [comment]
@PrometheusPi I removed the draft status because from your tests it looks like all is fine.

**Comment by PrometheusPi** [comment]
@psychocoderHPC thanks for fixing this problem. 
@finnolec You can now do your analysis with today's `dev`. 
@nicowrobel If you update to `dev`, you can simplify your analysis.
