### PR TITLE
Fix and modernize the generation scheme for MPI communication tags

### LINKED ISSUE #982: MPI tag needs range check
Tags used for MPI communication needs a check that they were not out of range.

`MPI_TAG_UB` defines the upper limit for tags.

see discussion in #958

### PR DESCRIPTION
**Pull request by sbastrakov**
The old scheme was causing some tags to be outside of the valid range #982.
Apply fixes and modernization of the tag generation scheme.
Document the requirements of the new scheme.

The remaining pieces of `picongpu::CommunicationTag` are no longer used for communication.
But they are left to keep the field solver traits, to be fixed in a following PR.

Resolves #982.
@jprotze thanks for reporting the issue. Hopefully this PR solves it, but I haven't tested it fully yet, will continue tomorrow.

### CODE REVIEW

**Comment by sbastrakov** [comment]
My Hemera test job is still in the queue. Small runs on the dev system worked fine.

**Comment by sbastrakov** [comment]
The test passed, ready for review @psychocoderHPC !

File: include/picongpu/simulation_types.hpp [hunk 1]
```diff
@@ -34,16 +34,14 @@
 
 namespace picongpu
 {
-    //! define all elements which can send and resive
-
+    /** Legacy communication tags
+     *
+     * Now only used for some field traits, to be removed soon
+     */
     enum CommunicationTag
```
Comment (psychocoderHPC) [inline include/picongpu/simulation_types.hpp:41]: Can we rename this type to something else, it is now only used to get the margins. 
As your new doxygen says it is no MPI communication tag anymore: https://github.com/ComputationalRadiationPhysics/picongpu/pull/3558/files#diff-ef03a551bc4457d540a9f7b8ee58246c94e3014958928ac33da6fd353a3c0d1dR82

It is something like an alias for the buffer/field. Maybe we should name it `fieldAlias`?

File: include/pmacc/particles/memory/buffers/ParticlesBuffer.hpp [hunk 2]
```diff
@@ -196,12 +197,16 @@ namespace pmacc
...
-                true,
-                false);
+            /* Generate a new tag from this type
+             *
+             * The tag is the same each time this method is called (per instantiation of this template).
+             * Here it is fine, as there is the only instance object, and
+             * exchangeMemoryIndexer->addExchangeBuffer() requires the same tag on each call
+             */
+            using This = ParticlesBuffer<T_ParticleDescription, SuperCellSize_, T_DeviceHeap, DIM>;
+            auto const newTag = traits::GetUniqueTypeId<This, uint32_t>::uid();
```
Comment (psychocoderHPC) [inline include/pmacc/particles/memory/buffers/ParticlesBuffer.hpp:207]: It should be possible to write `auto const newTag = traits::GetUniqueTypeId<ParticlesBuffer, uint32_t>::uid();`

File: include/pmacc/traits/GetUniqueTypeId.hpp [hunk 3]
```diff
@@ -73,6 +73,8 @@ namespace pmacc
         /** Get next available type id
          *
          * Warning: is not thread-safe.
+         * Warning: when using it to generate matching tags from multiple MPI ranks, ensure the same call order.
```
Comment (psychocoderHPC) [inline include/pmacc/traits/GetUniqueTypeId.hpp:76]: could you please use: `@warning` for this and the line above.

**Review by psychocoderHPC — CHANGES_REQUESTED** [review]

File: include/picongpu/simulation_types.hpp (hunk 1 above)
Comment (sbastrakov) [reply include/picongpu/simulation_types.hpp:41]: I will remove it in the next PR after this is merged

File: include/pmacc/particles/memory/buffers/ParticlesBuffer.hpp (hunk 2 above)
Comment (sbastrakov) [reply include/pmacc/particles/memory/buffers/ParticlesBuffer.hpp:207]: Ah, yes, I am always forgetting it

File: include/picongpu/simulation_types.hpp (hunk 1 above)
Comment (psychocoderHPC) [reply include/picongpu/simulation_types.hpp:41]: I am fine to move it into a follow up PR

**Comment by sbastrakov** [comment]
Thanks @psychocoderHPC . I've pushed a fix to the two latter points as `--amend`. The first one will be fixed in a follow-up PR by removing this `enum` alltogether - I didn't want to make this unrelated change as part of this PR.

File: include/pmacc/traits/GetUniqueTypeId.hpp [hunk 4]
```diff
@@ -72,7 +72,9 @@ namespace pmacc
 
         /** Get next available type id
          *
-         * Warning: is not thread-safe.
+         * \warning is not thread-safe.
```
Comment (psychocoderHPC) [inline include/pmacc/traits/GetUniqueTypeId.hpp:75]: Note please use next time `@warning` see https://github.com/ComputationalRadiationPhysics/contributing/blob/master/codingGuideLines/cpp.md#5-doxygen-comments

**Review by psychocoderHPC — APPROVED** [review]
