### PR TITLE
remove Bremsstrahlung and Synchrotron radition extension

### LINKED ISSUE #4193: example “bremsstrahlung"
I ran the calculation example “bremsstrahlung" provided by picongpu, and used paraview to post process the `.h5` file of the analog output, and got the results as shown in the figure below. I suspect the results are incorrect, because they are inconsistent with the results shown in the paper, especially the photon energy density is empty. I don't know where the problem is. Thank you very much for giving me some guidance.

1. data/5000/fields/e_all_chargeDensity
B8E)XS Q4WN{67)}CTXZX9Q
2. data/5000/fields/E/X
H~SJ8VRX` M 9(A4SV%CPWO
3.data/5000/fields/ph_all_chargeDensity and data/5000/fields/ph_all_energyDensity
7 47S 50G73CW0QW~UPC$43

### PR DESCRIPTION
**Pull request by psychocoderHPC**
close #4193 #2283

- both extentions are written in CUSTL and blocking further development
- remove Bremsstrahlungs example

last version with both extensions: https://github.com/ComputationalRadiationPhysics/picongpu/tree/2ad8de9beb5cd566a1647feb2be57092a6c00c0f

### CODE REVIEW

File: include/picongpu/simulation/control/Simulation.hpp [hunk 1]
```diff
@@ -65,30 +65,6 @@
 #include <pmacc/mappings/kernel/MappingDescription.hpp>
 #include <pmacc/mappings/simulation/GridController.hpp>
 #include <pmacc/mappings/simulation/SubGrid.hpp>
-#include <pmacc/random/RNGProvider.hpp>
```
Comment (PrometheusPi) [inline include/picongpu/simulation/control/Simulation.hpp:68]: are you sure about removing all this?

Comment (PrometheusPi) [reply include/picongpu/simulation/control/Simulation.hpp:68]: sorry - is introduced later

**Review by PrometheusPi — APPROVED** [review]
