### PR TITLE
fix signal handling

### LINKED ISSUE #5592: Broken signaling
Current signalling implementation can run into deadlocks. Also affects `--checkpoint.timePeriod` since this is using "fake" signals. 

The way we handle signalling for checkpointing and or shutdown requires collective MPI communication. The reason for that is that we have to establish the next common timestep since some ranks may be further ahead in computation (we do not synchronize every timestep). 

Currently, we let one more timestep run before waiting for the collective communication in signalling to ensure that we do not run into a deadlock in a conflict with a different collective operation within the simulation loop. But, this is not enough! openpmd IO read and write operations  (`flush()`) are collective. In addition to this, according to @psychocoderHPC, we explicitly synchronize before running collective IO operations with `MPIBarrier`. Since the IO is usually not done on every step, the current solution is not sufficient. (Ranks could be more than 1 step apart). 

As discussed with @psychocoderHPC, we should switch our Barrier before IO to a nonblocking one and keep checking for signals while waiting for the synchronization. 

For example like that:
```c++
MPI_Request ioBarrierMPI = MPI_REQUEST_NULL;
MPI_CHECK(MPI_Ibarrier(
Environment<DIM>::get().GridController().getCommunicator().getMPIComm(),
&ioBarrierMPI));
// Keep checking signals until all ranks reach this point. Other ranks may still receive and try to
// handle a signal.
Manager::getInstance().waitFor(
    [&]() -> bool
    {
        MPI_Status mpiBarrierStatus;
        int flag = 0;
        MPI_CHECK(MPI_Test(&ioBarrierMPI, &flag, &mpiBarrierStatus));
        checkSignals(currentStep);
        return flag != 0;
    });
```

Not sure how `checkSignals` needs to change? I think now the mpi reduce in `checkSignals` can be blocking, and we only need to call this method once. 

A similar issue happens at the end of the simulation, when some ranks already finished, but  others are still running and checking for signals. With that, there is a risk of a deadlock  in the mpi reduce, whenever the simulation receives signals shortly before finishing . Fixing this is as simple as adding the same `IBarrier` after the simulation loop in `SimulationHelper`.

We also decided to stop handling any further checkpoints in 'checkSignals' if all ranks already decided on finishing the simulation early. This can be achieved by adding another boolean state to the `SimulationHelper`.

### PR DESCRIPTION
**Pull request by psychocoderHPC**
fix #5592

The current implementation runs under special conditions into a deadlock,s see #5592.
Additionally,y this PR changes how signals are stored to allow the user to send signals during the simulation is blocked by MPI calls or
calculations multiple times.
Such multi signal send could also happen if the user is sending a signal and the batch system triggers a signal too.

- Signal handling is moved into an event system task and a new category of tasks (cooperative tasks) is added.
- provide a shorthand for a global blocking MPI barrier which is event system aware `eventSystem::mpiBlocking()`

Co-authored-by: Paweł Ordyna <p.ordyna@hzdr.de>

I tested this PR by starting a simulation with two MPI ranks and send signal by hand to each process, to guarantee the signal never arrives within the same time step. Additionally, I send signals during the IO to test that we do not miss signals when the simulation is blocked and not processing the event system.

### CODE REVIEW

**Comment by pordyna** [comment]
Nice! But we also need to replace the barrier in plugins and where we load density from openpmd.

File: include/pmacc/simulationControl/Checkpointing.hpp [hunk 1]
```diff
@@ -154,13 +154,11 @@ namespace pmacc::simulationControl
                  * for the checkpoint writing */
                 alpaka::wait(manager::Device<ComputeDevice>::get().current());
 
-                // avoid deadlock between not finished PMacc tasks and MPI_Barrier
-                eventSystem::getTransactionEvent().waitForFinished();
+                /* can be spared for better scaling, but allows to spare the
+                 * time for checkpointing if some ranks died */
+                Environment<>::get().mpiBarrier();
 
                 GridController<DIM>& gc = Environment<DIM>::get().GridController();
```
Comment (pordyna) [inline include/pmacc/simulationControl/Checkpointing.hpp:153]: I think we do not need the grid controller anymore here

**Review by pordyna — CHANGES_REQUESTED** [review]
Like in the previous comment, we need to replace the barrier before all collectives. I will test this without plugins on perlmutter.

File: include/pmacc/simulationControl/Checkpointing.hpp (hunk 1 above)
Comment (psychocoderHPC) [reply include/pmacc/simulationControl/Checkpointing.hpp:153]: It is used in line 164

**Comment by pordyna** [comment]
Another thing @psychocoderHPC 
### Need to await / finalize mpi communication in last step
https://github.com/ComputationalRadiationPhysics/picongpu/blob/8a18015b7947782840032e988b9786e06cecd498/include/pmacc/simulationControl/SimulationHelper.cpp#L331
likely need to be:
`if((currentStep != 0u && handleSignalAtStep == currentStep)
           || currentStep == Environment<>::get().SimulationDescription().getRunSteps())`
Otherwise, if we start handling in the last step or at the end of the simulation, we never finalize the non-blocking communication in signalling.

### Checkpoint in last step
I think this is save as it is, but I am not 100% sure. We can not land in a situation where 
https://github.com/ComputationalRadiationPhysics/picongpu/blob/8a18015b7947782840032e988b9786e06cecd498/include/pmacc/simulationControl/SimulationHelper.cpp#L353
this is called with `signalMaxTimestep` equal the total simulation steps and some steps are already after the last call to checkpointing.
I think it is either:  Checkpoint signal is handled first in the step before the last step, and the second call to `checkSignals` happens in the last step before the last call to checkpointing. Checkpoint is written in the last step. 
Or the signal is handled for the first time in the last step or at the end of the simulation, in that case `signalMaxTimestep` will be max steps +1 and no rank will ever try to write it, so there is no risk of a deadlock.

**Comment by psychocoderHPC** [comment]
@pordyna I refactored this PR to address the issues you pointed too.

**Review by pordyna — APPROVED** [review]
