### PR TITLE
Disable checkpointing properly if openPMD is missing

### LINKED ISSUE #5480: checkpoint flags still exist without openPMD
When compiling PIConGPU without openPMD, the help still shows options for checkpoints and thus might hide the fact that checkpointing will not work.

### PR DESCRIPTION
**Pull request by ikbuibui**
- [x]  #5492 needs to be merged before this.

Moves checkpointing simulation control in its own class
Checkpoint class now has a compile time toggle to disable checkpoint/restart functionality (fixes #5480)
Simplified restart state management and changed from using bools to an enum tracking state

### CODE REVIEW

File: include/pmacc/simulationControl/Checkpointing.hpp [hunk 1]
```diff
@@ -0,0 +1,374 @@
...
+                                "Restart failed. No checkpoints found and no '--checkpoint.restart.step' provided.");
+                        }
+                        restartState = RestartState::FAILED;
+                        return false;
+                    }
+                    restartStep = checkpoints.back();
+                }
+
+                // Checkpoints are expected to be sorted chronologically.
+                bool const stepFound = std::binary_search(checkpoints.cbegin(), checkpoints.cend(), restartStep);
```
Comment (ikbuibui) [inline include/pmacc/simulationControl/Checkpointing.hpp]: I have this logic here

File: include/picongpu/simulation/control/Simulation.hpp [hunk 2]
```diff
@@ -69,6 +70,7 @@
 #include <pmacc/particles/traits/FilterByIdentifier.hpp>
 #include <pmacc/random/RNGProvider.hpp>
 #include <pmacc/random/methods/methods.hpp>
+#include <pmacc/simulationControl/Checkpointing.hpp>
```
Comment (chillenzer) [inline include/picongpu/simulation/control/Simulation.hpp:73]: I would have expected `Checkpoint.hpp` but I presume you are distinguishing it from a single checkpoint (like referencing iteration 4892)?

File: include/pmacc/simulationControl/Checkpointing.hpp [hunk 3]
```diff
@@ -0,0 +1,440 @@
...
+
+        if(auto it = stateToString.find(state); it != stateToString.end())
+        {
+            out << it->second;
+        }
+        else
+        {
+            // Handle unknown enum values gracefully.
+            out << "UNKNOWN_RESTART_STATE(" << static_cast<int>(state) << ")";
+        }
```
Comment (chillenzer) [inline include/pmacc/simulationControl/Checkpointing.hpp]: Let's hope, we've never gotta do this!

File: include/pmacc/simulationControl/Checkpointing.hpp [hunk 4]
```diff
@@ -0,0 +1,440 @@
...
+     * @return The input stream.
+     */
+    inline std::istream& operator>>(std::istream& in, RestartState& state)
+    {
+        static std::unordered_map<std::string, RestartState> const stringToState
+            = {{"disabled", RestartState::DISABLED},
+               {"try", RestartState::TRY},
+               {"force", RestartState::FORCE},
+               {"success", RestartState::SUCCESS},
+               {"failed", RestartState::FAILED}};
```
Comment (chillenzer) [inline include/pmacc/simulationControl/Checkpointing.hpp]: Should we extract this? Having to update this in multiple places seems bound to fail. On the other hand, we'll hopefully not really have to update this ever.

File: include/pmacc/simulationControl/Checkpointing.hpp [hunk 5]
```diff
@@ -0,0 +1,440 @@
...
+        in >> token;
+
+        if(auto it = stringToState.find(token); it != stringToState.end())
+        {
+            state = it->second;
+        }
+        else
+        {
+            // If the token is not a valid state, set the stream's failbit.
+            // boost::program_options will catch this and report an error to the user.
```
Comment (chillenzer) [inline include/pmacc/simulationControl/Checkpointing.hpp]: Wow! Dark magic. Why not just throw yourself here?

File: include/pmacc/simulationControl/Checkpointing.hpp [hunk 6]
```diff
@@ -0,0 +1,440 @@
...
+        bool doSoftRestart()
+        {
+            static uint32_t nthSoftRestart = 0;
+            if(nthSoftRestart <= softRestarts)
+            {
+                nthSoftRestart++;
+                return true;
+            }
+            return false;
+        }
```
Comment (chillenzer) [inline include/pmacc/simulationControl/Checkpointing.hpp]: Not guarded by `checkpointingEnabled`.

File: include/pmacc/simulationControl/Checkpointing.hpp [hunk 7]
```diff
@@ -0,0 +1,440 @@
...
+     * (checkpointing) and to resume a simulation from a saved state (restarting).
+     * The checkpointing can be triggered based on simulation steps or wall-clock time.
+     * The entire functionality can be enabled or disabled at compile time via the
+     * `checkpointingEnabled` template parameter.
+     *
+     * @tparam checkpointingEnabled A boolean to enable/disable checkpointing features.
+     */
+    template<bool checkpointingEnabled>
+    struct Checkpointing
+    {
```
Comment (chillenzer) [inline include/pmacc/simulationControl/Checkpointing.hpp]: I strongly dislike the approach of guarding each individual function body with an `if constexpr` because you have to repeat this over and over again. I would have expected to just provide a specialisation
```C++
template<>
struct Checkpointing<false> {
    void registerHelp(...) {}
    ...
};
```
Is there a strong reason for your design?

File: include/pmacc/simulationControl/Checkpointing.hpp [hunk 8]
```diff
@@ -0,0 +1,440 @@
...
+                    ("checkpoint.period", po::value<std::string>(&checkpointPeriod),
+                     "Period for checkpoint creation [interval(s) based on steps]")
+                    ("checkpoint.timePeriod", po::value<std::uint64_t>(&checkpointPeriodMinutes),
+                     "Time periodic checkpoint creation [period in minutes]")
+                    ("checkpoint.directory", po::value<std::string>(&checkpointDirectory)->default_value(checkpointDirectory),
+                     "Directory for checkpoints");
+                // clang-format on
+                // translate checkpointPeriod string into checkpoint intervals
+                seqCheckpointPeriod = pluginSystem::toTimeSlice(checkpointPeriod);
+            }
```
Comment (chillenzer) [inline include/pmacc/simulationControl/Checkpointing.hpp]: Diff'ed against the removed parts from `SimulationHelper` and looks correct.

File: include/pmacc/simulationControl/SimulationHelper.cpp [hunk 9]
```diff
@@ -27,52 +27,33 @@
...
-        {
-            // notify all concurrent threads to exit
-            std::unique_lock<std::mutex> lk(this->concurrentThreadMutex);
-            exitConcurrentThreads.notify_all();
-        }
-        // wait for time triggered checkpoint thread
-        if(checkpointTimeThread.joinable())
-            checkpointTimeThread.join();
-
+        checkpointing.endTimeBasedCheckpointing();
```
Comment (chillenzer) [inline include/pmacc/simulationControl/SimulationHelper.cpp]: Wow, camel case is not great here. I had to dig into the code to realise that it's not an apocalytic "end-time-based checkpointing" but it's just "ending the time-based checkpointing". Could we rename to "finish"/"cancel"/...?

(I would have been curious what an apocalyptic "end-time-based checkpointing" could look like, though, if you ever want to implement one...)

**Review by chillenzer — CHANGES_REQUESTED** [review]
Partial review.

File: include/picongpu/simulation/control/Simulation.hpp (hunk 2 above)
Comment (ikbuibui) [reply include/picongpu/simulation/control/Simulation.hpp:73]: Yeah, this was the main cause of my unease.

File: include/pmacc/simulationControl/Checkpointing.hpp (hunk 6 above)
Comment (chillenzer) [inline include/pmacc/simulationControl/Checkpointing.hpp]: Please rename this function. Starting with `do...` suggests heavily that it actually `do`es something. In the `while` context it's used in it doesn't read too bad but out of context it's weird. You might want to try something along the lines of `moreSoftRestartAttemptsAllowed`.

File: include/pmacc/simulationControl/Checkpointing.hpp [hunk 10]
```diff
@@ -0,0 +1,440 @@
...
+                            while(exitConcurrentThreads.wait_until(
+                                      lk,
+                                      std::chrono::system_clock::now() + std::chrono::minutes(checkpointPeriodMinutes))
+                                  == std::cv_status::timeout)
+                            {
+                                signal::detail::setCreateCheckpoint(1);
+                            }
+                        });
+            }
+        }
```
Comment (chillenzer) [inline include/pmacc/simulationControl/Checkpointing.hpp]: Same here: `do...` suggests that it does something while it actually rather `start...`s or `activate...`s.

**Review by chillenzer — CHANGES_REQUESTED** [review]
Looks okay to me otherwise. Please do the marked renamings.

**Comment by PrometheusPi** [comment]
@ikbuibui what is the status of this PR?

**Comment by ikbuibui** [comment]
I still need to address the requested changes, will happen sometime this week.

File: include/pmacc/simulationControl/SimulationHelper.cpp (hunk 9 above)
Comment (ikbuibui) [reply include/pmacc/simulationControl/SimulationHelper.cpp]: renamed to `finishTimeBasedCheckpointing`

File: include/pmacc/simulationControl/Checkpointing.hpp (hunk 7 above)
Comment (ikbuibui) [reply include/pmacc/simulationControl/Checkpointing.hpp]: Used your suggestion

File: include/pmacc/simulationControl/Checkpointing.hpp (hunk 6 above)
Comment (ikbuibui) [reply include/pmacc/simulationControl/Checkpointing.hpp]: We allowed restart attempts, even without checkpoints (from the start of the simulation). This only maintains old functionality.

File: include/pmacc/simulationControl/Checkpointing.hpp (hunk 5 above)
Comment (ikbuibui) [reply include/pmacc/simulationControl/Checkpointing.hpp]: I prefer to leave the responsibility of IO to boost po

File: include/pmacc/simulationControl/Checkpointing.hpp (hunk 4 above)
Comment (ikbuibui) [reply include/pmacc/simulationControl/Checkpointing.hpp]: Unified

File: include/pmacc/simulationControl/Checkpointing.hpp (hunk 6 above)
Comment (ikbuibui) [reply include/pmacc/simulationControl/Checkpointing.hpp]: renamed to `canSoftRestart`. But as I type it now i think this name has the `empty` problem. It is not clear if the caller asking or telling

File: include/pmacc/simulationControl/Checkpointing.hpp (hunk 10 above)
Comment (ikbuibui) [reply include/pmacc/simulationControl/Checkpointing.hpp]: renamed to `startTimeBasedCheckpointing` to complement the `finishTimeBasedCheckpointing`

File: include/pmacc/simulationControl/Checkpointing.hpp (hunk 6 above)
Comment (ikbuibui) [reply include/pmacc/simulationControl/Checkpointing.hpp]: I moved it to this class just to keep the user facing `checkpoint.restart.loop` input

Comment (ikbuibui) [reply include/pmacc/simulationControl/Checkpointing.hpp]: now changed to the more verbose  `tryConsumeRestartAttempt`

File: include/pmacc/simulationControl/Checkpointing.hpp (hunk 5 above)
Comment (chillenzer) [reply include/pmacc/simulationControl/Checkpointing.hpp]: Is this an idiomatic and documented way to use boost po? If so, could you please point me to a reference? Haven't found it anywhere in [the docs](https://www.boost.org/doc/libs/latest/doc/html/program_options.html).

File: include/pmacc/simulationControl/Checkpointing.hpp (hunk 7 above)
Comment (chillenzer) [reply include/pmacc/simulationControl/Checkpointing.hpp]: Looks good. Two tiny things:
- Shall we declare the default class template without a definition and define only the specialisations?
```C++
template<bool checkpointingEnabled>
struct Checkpointing;

template<>
structu Checkpointing<true> {
...
```
- Boolean interfaces are an anti-pattern (see e.g. [this explanation and example](https://docs.astral.sh/ruff/rules/boolean-type-hint-positional-argument/)). I'd prefer to have this as an enum.
```C++
enum class CheckpointingAvailability {
...

template<CheckpointingAvailability checkpointingEnabled>
struct Checkpointing {
...
```

Just to be explicit: The second without the first would not be a good idea because the second opens the possibility of more modes.

Comment (chillenzer) [reply include/pmacc/simulationControl/Checkpointing.hpp]: PS: Not blocking.

File: include/pmacc/simulationControl/Checkpointing.hpp (hunk 6 above)
Comment (chillenzer) [reply include/pmacc/simulationControl/Checkpointing.hpp]: I don't like that you still have a verb in the name that could be read as an imperative because it still conveys the meaning of doing something. Options would be any of the following:
- third person forms of a verb, particularly `is...`, `has...` but also `allows...`
- any participle `...allowed`, `...left`, etc.
- any attribute `...available`

Suggestions:
```C++
while(checkpointing.softRestartAttemptsAreLeft())
while(checkpointing.hasSoftRestartAttemptsLeft())
while(checkpointing.allowsSoftRestartAttempts())
```

File: include/pmacc/simulationControl/Checkpointing.hpp (hunk 5 above)
Comment (ikbuibui) [reply include/pmacc/simulationControl/Checkpointing.hpp]: Using a custom validator is most likely the idiomatic way to do it (discussed in the SO question below), but I chose the (IMO) simpler option.
I took over the solution from [here](https://stackoverflow.com/questions/27526817/input-stream-operator-lookup-order-with-boost-program-options)

Comment (ikbuibui) [reply include/pmacc/simulationControl/Checkpointing.hpp]: I can add a validate as well if you think it helps

File: include/pmacc/simulationControl/Checkpointing.hpp (hunk 7 above)
Comment (ikbuibui) [reply include/pmacc/simulationControl/Checkpointing.hpp]: Changed

File: include/pmacc/simulationControl/Checkpointing.hpp (hunk 6 above)
Comment (ikbuibui) [reply include/pmacc/simulationControl/Checkpointing.hpp]: using `hasSoftRestartAttemptsLeft`

File: include/pmacc/simulationControl/Checkpointing.hpp [hunk 11]
```diff
@@ -0,0 +1,508 @@
...
+                            "Restart failed. No checkpoints found and no '--checkpoint.restart.step' provided.");
+                    }
+                    restartState = RestartState::FAILED;
+                    return false;
+                }
+                restartStep = checkpoints.back();
+            }
+
+            // Checkpoints are expected to be sorted chronologically.
+            bool const stepFound = std::binary_search(checkpoints.cbegin(), checkpoints.cend(), restartStep);
```
Comment (chillenzer) [inline include/pmacc/simulationControl/Checkpointing.hpp]: This assertion is wrong, I believe: You've got the `addCheckpoint` which will push a random number to the end of the vector. Even if that's not an immediate bug currently due to the precise path through the code that's taken to arrive here, I still think that the performance gain at this point is not worth risking this to become a problem.

File: include/pmacc/simulationControl/Checkpointing.hpp [hunk 12]
```diff
@@ -0,0 +1,508 @@
...
+                std::unique_lock<std::mutex> lk(this->concurrentThreadMutex);
+                exitConcurrentThreads.notify_all();
+            }
+            // wait for time triggered checkpoint thread
+            if(checkpointTimeThread.joinable())
+                checkpointTimeThread.join();
+        }
+
+        /* Returns whether a restart needs to be performed */
+        bool checkRestart(uint32_t& step)
```
Comment (chillenzer) [inline include/pmacc/simulationControl/Checkpointing.hpp:237]: If you have that comment right above, why not?
```suggestion
        bool restartNeedsToBePerformed(uint32_t& step)
```

**Review by chillenzer — CHANGES_REQUESTED** [review]

File: include/pmacc/simulationControl/Checkpointing.hpp (hunk 12 above)
Comment (ikbuibui) [reply include/pmacc/simulationControl/Checkpointing.hpp:237]: `restartNeedsToBePerformed` also sounds like an instruction to do something

Comment (chillenzer) [reply include/pmacc/simulationControl/Checkpointing.hpp:237]: I see... I was thinking about
```C++
if(checkpointing.restartNeedsToBePerformed)
```
which reads quite clearly but that might be just to my ears. This is not blocking. We can keep it as is.

File: include/pmacc/simulationControl/Checkpointing.hpp (hunk 11 above)
Comment (ikbuibui) [reply include/pmacc/simulationControl/Checkpointing.hpp]: This is a good point, I now replaced this with a more resilient reversed find, since I think the most recent matching checkpoint should be preferred over older ones (in the event such a case occurs)

File: include/pmacc/simulationControl/Checkpointing.hpp (hunk 6 above)
Comment (chillenzer) [reply include/pmacc/simulationControl/Checkpointing.hpp]: Okay. Not 100% happy with the code duplication that happened due to separating the template specialisations but I'll let that slip.

File: include/pmacc/simulationControl/Checkpointing.hpp (hunk 5 above)
Comment (chillenzer) [reply include/pmacc/simulationControl/Checkpointing.hpp]: If that's not an officially supported protocol, I'd refrain from using this obscure way to signal a failure. If it's not official interface, boost po would be allowed to change this behaviour without further notice, e.g., just swallow the failbit and keep going. I can see the advantages of the "initialisation = validation" approach that Pydantic is taking as well but I wouldn't do so at the expense of relying on implementation details of a code we don't control. 

My suggestion (admittedly I haven't checked the `validate` protocol, so please fill in the blanks):
```C++
std::optional<RestartState> stringToRestartState(std::string const given) {
    // ...
    return it == ...end()? std::nullopt : it->first;
}

inline auto validate(std::istream& in, RestartState& state) {
    // ...
    auto state = stringToRestartState(token);
    if (not state.has_value()) {
        // ...
    }
    return ...
}

inline std::istream& operator>>(std::istream& in, RestartState& state) {
    auto state = stringToRestartState(token);
    // ...
}
```
(Also I'm presuming that this is not at all performance critical or anything, so not taking care of how many copies we make here. etc.)

Comment (ikbuibui) [reply include/pmacc/simulationControl/Checkpointing.hpp]: I was able to use `validate` and get away without defining the stream operators at all as there is an overload of `implicit_value` which takes the string representation.

**Review by chillenzer — APPROVED** [review]
Thanks for bearing with me for so long. We finally made it!
