### PR TITLE
Fix checkpointing regression introduced by TOML PR

### LINKED ISSUE #3977: Checkpoint plugin not processing options correctly?
As noted during the crusher hackathon, the error
```bash
Unhandled exception of type 'St13runtime_error' with message 'There is no default value defined for the option file and idx is out of range', terminating
```
is thrown when using the checkpoint plugin.

cc'ing @franzpoeschel 

Using picongpu-dev as of today and TBG config attached
[tbg_checkpoint.md](https://github.com/ComputationalRadiationPhysics/picongpu/files/8036197/tbg_checkpoint.md)

### PR DESCRIPTION
**Pull request by franzpoeschel**
...... nothing to be seen here ........

close #3977
Bug introduced by #3720

When running a checkpoint, the openPMD plugin must not attempt to read the cmd parameter `--checkpoint.openPMD.file` because it's not there. Instead, the `--checkpoint.file` parameter is used.

### CODE REVIEW

File: include/picongpu/plugins/openPMD/openPMDWriter.hpp [hunk 1]
```diff
@@ -373,23 +377,40 @@ make sure that environment variable OPENPMD_BP_BACKEND is not set to ADIOS1.
                 }
             case ConfigurationVia::CommandLine:
```
Comment (franzpoeschel) [inline include/picongpu/plugins/openPMD/openPMDWriter.hpp:378]: Note that we don't need to fix the `ConfigurationVia::Toml` path since checkpoints cannot be configured via TOML.

**Comment by steindev** [comment]
Tested writing checkpoints with this fix and it works now. Will merge.

**Review by steindev — APPROVED** [review]
