### PR TITLE
openPMD plugin: no hardcoding of float_X in writeField()

### LINKED ISSUE #3754: openPMD plugin hard-relies on fields being float_X internally
Currently there are 3 places in its `writeField()` that hard-rely on it:

- [compile-time check](https://github.com/ComputationalRadiationPhysics/picongpu/blob/77b662ce6eb7359aea5291e9d21b9ebfc8509fab/include/picongpu/plugins/openPMD/openPMDWriter.hpp#L939-L940)
- [store chunk call](https://github.com/ComputationalRadiationPhysics/picongpu/blob/77b662ce6eb7359aea5291e9d21b9ebfc8509fab/include/picongpu/plugins/openPMD/openPMDWriter.hpp#L1042). Unrelated, but do we need this wrapper for that openPMD API function now?
- [this indexing](https://github.com/ComputationalRadiationPhysics/picongpu/blob/77b662ce6eb7359aea5291e9d21b9ebfc8509fab/include/picongpu/plugins/openPMD/openPMDWriter.hpp#L1078) would be incorrect for other data types

It's not a bug per se, as the different case just wouldn't compile. But it would make it difficult to use in some other cases, e.g. now I am trying to add output of RNG internal states, which are also a field (defined per cell) but not `float_X`. And so such a `writeField()` can't be directly used. It's also not clear now why is it hardcoded now (cuz of openPMD API ? idk), it would help to document it more clearly.

@franzpoeschel it would be nice if you can have a look there at some point.

### PR DESCRIPTION
**Pull request by franzpoeschel**
The function `writeField()` *is* already templated on the type to use for writing, but so far does a compile-time check if that type is `float_X`. Make it generic, close #3754.

TODO:
- [x] Check that writing still works as usual. For this PR, I needed to make the `fieldBuffer` of type `char` and `reinterpret_cast` the data pointer. This is asking for trouble, but necessary.
- [x] Check that other datatypes work now. I'll leave this one to @sbastrakov.

### CODE REVIEW

**Comment by franzpoeschel** [comment]
I'm not quite sure what the CI is trying to tell me

**Comment by psychocoderHPC** [comment]
I restarted your CI job, maybe the IT department restarted the CI demon.

**Review by psychocoderHPC — DISMISSED** [review]

**Comment by franzpoeschel** [comment]
For the first todo point, I used [this script](https://github.com/ComputationalRadiationPhysics/picongpu/pull/2966#issuecomment-607883172) to compare the output written by the openPMD plugin before and after this PR (all written with HDF5):

```
[E][x]
max rel. error: 0.032240960747003555
mean error:     8.44965543365106e-05
std rel. error: 0.0003429955686442554

[E][y]
max rel. error: 0.050970982760190964
mean error:     7.313640526263043e-05
std rel. error: 0.0006541579496115446

[E][z]
max rel. error: 0.0453251376748085
mean error:     0.0001220170670421794
std rel. error: 0.0007794760749675333

[B][x]
max rel. error: 0.0062445891089737415
mean error:     6.569224933627993e-05
std rel. error: 0.00018595463188830763

[B][y]
max rel. error: 0.22249464690685272
mean error:     0.00019813785911537707
std rel. error: 0.001610537408851087

[B][z]
max rel. error: 0.056849975138902664
mean error:     5.284184226184152e-05
std rel. error: 0.0004599449457600713
```

As a comparison for what values we should accept as ok, this here compares two openPMD datasets both written without this PR:
```
[E][x]
max rel. error: 0.05665963143110275
mean error:     9.044402395375073e-05
std rel. error: 0.0006765848374925554

[E][y]
max rel. error: 0.08794880658388138
mean error:     8.561994036426768e-05
std rel. error: 0.0008417890639975667

[E][z]
max rel. error: 0.027569260448217392
mean error:     0.00010197158553637564
std rel. error: 0.0005569226341322064

[B][x]
max rel. error: 0.010704919695854187
mean error:     7.494685996789485e-05
std rel. error: 0.00021670920250471681

[B][y]
max rel. error: 0.19558413326740265
mean error:     0.00021599467436317354
std rel. error: 0.001453688833862543

[B][z]
max rel. error: 0.1924053430557251
mean error:     8.264483767561615e-05
std rel. error: 0.0012934181140735745
```

Looks overall like this PR does not change IO.

**Comment by psychocoderHPC** [comment]
@franzpoeschel Could you please run ` git commit --amend -a` in your terminal and force push to your fork that the CI is triggered again, manual triggering is not working.

**Comment by franzpoeschel** [comment]
> @franzpoeschel Could you please run ` git commit --amend -a` in your terminal and force push to your fork that the CI is triggered again, manual triggering is not working.

That apparently didn't work

**Review by psychocoderHPC — DISMISSED** [review]

**Comment by psychocoderHPC** [comment]
> > @franzpoeschel Could you please run ` git commit --amend -a` in your terminal and force push to your fork that the CI is triggered again, manual triggering is not working.
> 
> That apparently didn't work

I try to solve the issue, found out that the CI reports `The pipeline job activity limit was exceeded.`
I am currently searching if I can change the limit or if only the CI System admin is allowed to do it.

**Comment by psychocoderHPC** [comment]
PLease`amend` and force push again to trigger the CI. The problem that jobs get killed is not solved but the CI is now free and therefore all should pass.

File: include/picongpu/plugins/openPMD/openPMDWriter.hpp [hunk 1]
```diff
@@ -915,7 +913,6 @@ Make sure that environment variable OPENPMD_BP_BACKEND is not set to ADIOS1.
             static void writeField(
                 ThreadParams* params,
                 const uint32_t sizePtrType,
```
Comment (sbastrakov) [inline include/picongpu/plugins/openPMD/openPMDWriter.hpp:915]: Unrelated to this PR, but why is this variable here?

Comment (franzpoeschel) [reply include/picongpu/plugins/openPMD/openPMDWriter.hpp:915]: Good question, honestly I don't know. I can remove it, but then the CI would need to run again.

Comment (sbastrakov) [reply include/picongpu/plugins/openPMD/openPMDWriter.hpp:915]: It can also be done separately, was just wondering if that variable had some sense that I don't get.

Comment (franzpoeschel) [reply include/picongpu/plugins/openPMD/openPMDWriter.hpp:915]: >It can also be done separately

Done: https://github.com/ComputationalRadiationPhysics/picongpu/pull/3767

**Comment by sbastrakov** [comment]
Sorry, I didn't check it yet with other data types. I can only do it tomorrow.

**Comment by psychocoderHPC** [comment]
@franzpoeschel  could you please rebase your PR against dev to solve the merge conflict.

**Comment by franzpoeschel** [comment]
> @franzpoeschel could you please rebase your PR against dev to solve the merge conflict.

done

**Comment by sbastrakov** [comment]
I've checked with other datatype, it seems fine. Still not very easy to use for RNG states directly, as some more work with `isDomainBound` is required. But wrt this PR direction, all seems good

**Review by sbastrakov — APPROVED** [review]
