### PR TITLE
fix clang-cuda and boost compile

### LINKED ISSUE #3294: clang-cuda compile issues
Including some boost header when compiling with clang-cuda produce compile issues:

```
In file included from <built-in>:1:
In file included from /usr/lib/llvm-9/lib/clang/9.0.0/include/__clang_cuda_runtime_wrapper.h:36:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.5.0/../../../../include/c++/7.5.0/cmath:45:
In file included from /usr/include/math.h:290:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:53:13: error: exception specification in declaration does not match previous declaration
__MATHCALL (acos,, (_Mdouble_ __x));
            ^
```

Tested with clang 9 and 10

### PR DESCRIPTION
**Pull request by psychocoderHPC**
fix #3294

Solve invalid compiler detection in the clang-cuda device compile path.

### CODE REVIEW

File: include/picongpu/main.cpp [hunk 1]
```diff
@@ -18,6 +18,8 @@
  * If not, see <http://www.gnu.org/licenses/>.
  */
 
+#include "boost_workaround.hpp"
```
Comment (sbastrakov) [inline include/picongpu/main.cpp:21]: Why not `picongpu/boost_workaround.hpp` ? (Here and in `main.cpp`)
