### PR TITLE
Properly account for current background when deciding to skip adding J

### LINKED ISSUE #4244: Checks for current addition to E ignore current background
The check if current exists only considers species. However, [this part](https://github.com/ComputationalRadiationPhysics/picongpu/blob/67c50a27a7d417a92f4ae6a596f30fefc6805727/include/picongpu/simulation/stage/CurrentInterpolationAndAdditionToEMF.hpp#L92-L96) should also consider if current background is enabled.

Now with the current background enabled and no relevant species (not macroparticles, but species) PIConGPU would not actually add background current. This bugs seems to exist for about forever. However I doubt it was ever actually encountered as we generally always have species with currents (and if the rare situation and this bug happened the result would be obviously unexpected).

The existance of species should only be a condition for MPI communication. And the correct condition for adding currents should be existance of species or current background.

I will provide a fix shortly, now working on related things and that's how the problem was discovered.

### PR DESCRIPTION
**Pull request by sbastrakov**
Fixes #4244 , details are described there.

### CODE REVIEW

File: include/picongpu/simulation/stage/CurrentInterpolationAndAdditionToEMF.hpp [hunk 1]
```diff
@@ -127,6 +127,16 @@ namespace picongpu
                             fieldSolver.addCurrent<type::CORE + type::BORDER>();
                         }
                     }
+                    else
+                    {
+                        /* With no current from macroparticles, there is no need for communication.
```
Comment (psychocoderHPC) [inline include/picongpu/simulation/stage/CurrentInterpolationAndAdditionToEMF.hpp:132]: Let us check this tomorrow together. Field background is only created on `CORE+BORDER` therefore we need to read from the neighbors to have valid data in the guard for the binomial smoothing operation.
Nevertheless, we need to avoid scattering guard data twice into the border, we only need to read border data from neighbors into the guard.
I think 4 eyes should avoid introducing a new bug.

**Review by psychocoderHPC — CHANGES_REQUESTED** [review]

File: include/picongpu/simulation/stage/CurrentInterpolationAndAdditionToEMF.hpp (hunk 1 above)
Comment (sbastrakov) [reply include/picongpu/simulation/stage/CurrentInterpolationAndAdditionToEMF.hpp:132]: Oh true, let's discuss tomorrow.

Comment (sbastrakov) [reply include/picongpu/simulation/stage/CurrentInterpolationAndAdditionToEMF.hpp:132]: I think what you describe is another bug that is present regardless of thus PR

Comment (sbastrakov) [reply include/picongpu/simulation/stage/CurrentInterpolationAndAdditionToEMF.hpp:132]: Discussed offline, summarized in #4250 . Unrelated to this PR.

**Review by psychocoderHPC — APPROVED** [review]
