### PR TITLE
Fix checkpointing and output of PML fields for uneven domains

### LINKED ISSUE #3275: PML with uneven domains is not output and check pointed correctly
The logic of writing and reading of PML fields relies on the domains being of equal size. It equally concerns output and checkpointing. 

Here is the code that assumed it:  [1](https://github.com/ComputationalRadiationPhysics/picongpu/blob/fe322db49e69b09258691c4aa781769470fe693d/include/picongpu/plugins/hdf5/writer/Field.hpp#L119-L142), [2](https://github.com/ComputationalRadiationPhysics/picongpu/blob/fe322db49e69b09258691c4aa781769470fe693d/include/picongpu/plugins/hdf5/restart/RestartFieldLoader.hpp#L93-L115), and similar for the other two output plugins. The error is that while the allocated-for PML thickness is indeed the same (even for internal domains), that does not imply the buffer size is the same, as the latter also depends on the local domain size.

This concerns input/output only, not the correctness of the computational part. Note that the PML fields are actually not needed in the normal simulation output and their output is not enabled by default. However, for checkpointing they are required and enabled.

The incorrect behavior discovered by @Anton-Le

### PR DESCRIPTION
**Pull request by sbastrakov**
Fix #3275 for all three output backends.

Since the three output plugins we have are largely similar, the changes are basically copy-pasted in all 3 plugins. I deliberately did not go into abstracting and reusing, since this is a patch (to a patch for PML support) and the HDF5 and ADIOS plugins will (hopefully) be removed soon.

### CODE REVIEW

**Comment by sbastrakov** [comment]
Current status: the fix seems to work for a small example with uneven domains for the HDF5 backend. Now I will be testing a more complex setup, with moving window and decomposition along all 3 axes. And if that works will make similar changes for the other two output backends.

**Comment by sbastrakov** [comment]
Ready for review!

**Comment by sbastrakov** [comment]
cc @Anton-Le 
I tried on a small example using `gridDist`, and with this fix everything seemed to work.

**Comment by sbastrakov** [comment]
Note that this functionality is broken in the recent release, so we should perhaps make a backport afterwards.

**Comment by Anton-Le** [comment]
@sbastrakov Great! I will test it with the original problem.

**Comment by Anton-Le** [comment]
Great job! This fixes the problem of failed restarts for the setup it has first been observed in!

I also agree with @sbastrakov that this fix should be applied to the recent release.

**Comment by sbastrakov** [comment]
Thanks for checking @Anton-Le .

@psychocoderHPC could you review this PR?

File: include/picongpu/plugins/adios/ADIOSWriter.hpp [hunk 1]
```diff
@@ -556,23 +558,48 @@ class ADIOSWriter : public IIOBackend
...
             DataConnector &dc = Environment<>::get().DataConnector();
             auto field = dc.get< T_Field >( T_Field::getName() );
             fieldsSizeDims = precisionCast< uint64_t >( field->getGridLayout().getDataSpaceWithoutGuarding() );
             dc.releaseData( T_Field::getName() );
-            auto const & gridController = Environment<simDim>::get().GridController();
-            auto const numRanks = gridController.getGlobalSize();
-            auto const rank = gridController.getGlobalRank();
+            auto & gridController = Environment<simDim>::get().GridController();
+            auto const numRanks = uint64_t{ gridController.getGlobalSize() };
+            auto const rank = uint64_t{ gridController.getGlobalRank() };
```
Comment (psychocoderHPC) [inline include/picongpu/plugins/adios/ADIOSWriter.hpp:571]: Only a note: @sbastrakov and me discussed offline that the rank is not the best unique id as marker to load data. The reason is that we can not guarantee that the rank is deterministic.

Comment (psychocoderHPC) [reply include/picongpu/plugins/adios/ADIOSWriter.hpp:571]: We need to introduce a unique reproducible ID in pmacc. This should not be part of this PR and will break the compatibility of checkpoints written with this PR and later checkpoints.

Comment (sbastrakov) [reply include/picongpu/plugins/adios/ADIOSWriter.hpp]: Discussed offline, I will change MPI rank to the rank based on domain position. There is already `gridController.getScalarPosition()` for getting it.

Comment (sbastrakov) [reply include/picongpu/plugins/adios/ADIOSWriter.hpp]: Done.

**Comment by sbastrakov** [comment]
I've changed to ranks to local domain index, re-ran the tests and rebased. Ready for another review @psychocoderHPC .
