### PR TITLE
fix moving window moving speed

### LINKED ISSUE #1330: Moving Window: Too Slow
@BeyondEspresso discovered that the moving window implementation is broken in terms of correctness of speed. Currently, it moves a few percent too slow due to rounding errors.

To fix this reasonably, the implementation in [`simulationControl/MovingWindow.hpp`](https://github.com/ComputationalRadiationPhysics/picongpu/blob/c17cbf98292c2b0e29035dfd05186d811e4748e7/src/picongpu/include/simulationControl/MovingWindow.hpp) needs a full refactoring, is highly obfuscated, very old and needs doxygen documentation (we knew that at least). (In contrast, [the wiki](https://github.com/ComputationalRadiationPhysics/picongpu/wiki/PIConGPU-domain-definitions#moving-window) documents all its non-code aspects very well.)

### Code Analysis

It's very old, pre-git code and we are not surprised that there will be dragons :)

**PIConGPU Code**
Affected `MovingWindow` members:
 - private (central and to-be-redone API): `getCurrentSlideInfo`
 - public: `getSlideCounter`, `slideInCurrentStep`, `getWindow` (the last one is the only one that will actually update the offset)

`getWindow` is the *only one* that will actually update the offset members in `MovingWindow`, but is not triggered when actually doing the slide in `simulationControl/MySimulation.hpp` leaving the offsets partly outdated for some time.

**PMacc code**
`MySimulation` calls then `GridController::slide(...)` which then implements the offset calculation *again on it's own* in PMacc `mappings/simulation/GridController::updateLocalDomainOffset` that finally also updates the `SubGrid`. Also, it triggers `communication/CommunicatorMPI::slide`... . Finally, as a special feature, the `GridController` and `CommunicatorMPI` each implement a `setStateAfterSlides` that can be used to restart a simulation and "emulate" the number of slides it did before (for `SubGrid` and `CommunicatorMPI`) and return true if a slide has happened *for this MPI-rank*.

Again, `slide/setStateAfterSlides` calls will perform a slide as soon as called and are collective but return only true if *one was one of the GPUs that was moved from back to front*.

Last word on the `CommunicatorMPI`: even if documented called in-code precisely, it updates only the position in the 3D grid of MPI ranks (no manipulation of cell domain information or offsets). At time of slide the exchange partners are updated. An interesting and fishy member is `yoffset` which is together with `coords` defining a virtual layer for enumerating the MPI-rank positions in the domain decomposition since the `MPI_Cart_create` operation is expensive and only done once at the beginning of the sim. One wants a continuously, monotonically increasing numbered space of GPU positions after slides. Its member `updateCoordinates` might still need a good review but is unaffected as long as slides continue to happen in `y`.

### Proposed Refactoring

[WIP!]

"Slide" describes the moving of a whole plane of GPUs from the back of the simulation box to the front.

**Algorithm** (PIConGPU Code)
`MovingWindow` should first separate the *raw algorithm on moving window offset calculation* and the *manipulation of members*.

Raw members for algorithm:
 - `setStartAfterStep(uint32_t)`: start in steps; step after that the moving window starts to move (time offset for the moving starts, precision: one time step)
 - `setSpeed(float64_t)`: currently `c`
 - `int64_t getCurrentMovedCells( float32_t cellSizeInDir, uint32_t currentStep)`: current number of cells moved which is a scalar, not a 3D position, which makes the direction irrelevant

The `MovingWindow`'s member `window` should be a separate singleton as `SubGrid`, manipulated with the results from the previous class.

**Slide Detection** (PIConGPU Code)

To detect if a slide occurs after the current step (which is the connection to PMacc that controls MPI & reinit after sliding) one can simply [calculate](https://github.com/ComputationalRadiationPhysics/picongpu/wiki/PIConGPU-domain-definitions):
```C++
    // allows static load balancing in y later on
    bool isSlideAfterStep = (globalDomain.size - globalWindow.offset - globalWindow.size) == 0;
```

**Offset and Window Size Updates**

`SubGrid` is already there for *local domain* size and offset remembering and can be manipulated by all members. `Window` is regularly updated every time step and `SubGrid` only on slides.

PIConGPU now decides on a `slideDirection`.

PIConGPU (MySimulation) code logic at the beginning of a step:
 - `isSlideAfterStep(t-1)`
 - `isSliding = `GPU position in Communicator...(slideDirection) is back of box in that slideDirection
 - if `isSlideAfterStep`: slide GC/Communicator
   - offset updates `SubGrid` (assume cell in y equal for all GPUs):
     - `SubGrid.globalDomain.offset(slideDirection) += SubGrid.localDomain.size`
     - `SubGrid.localDomain.offset(slideDirection) = globalWindow.offset(slideDirection) + globalWindow.size(slideDirection) - SubGrid.localDomain.size`
 - `moveCells = MovingWindow::getCurrentMovedCells`
 - update `Window`:
   - (can be implemented in a `Window` member)
   - `globalWindow.offset = MovingWindow::getCurrentMovedCells - SubGrid.globalDomain.offset`
   - `localWindow.offset = SubGrid.localDomain.offset - globalWindow.offset`
     - `< 0 ?` (means back of simulation box): `localWindow.size -= moveCells`
   - `[local&global]Window.offset += moveCells`
   - if `localWindow.size <= 0`: (or `isSliding == true`):
     - `localWindow.size += SubGrid.localDomain.size`
     - `localWindow.offset = 0`

### PR DESCRIPTION
**Pull request by psychocoderHPC**
- re-implements internals of `MovingWindow::getCurrentSlideInfo(...)`
- fix rounding errors in moving window
- close #1330 Moving Window: Too Slow

This pull request solve the same issue than #1336 does but with the different implementation with less rounding magic.

**Documentation:**

- [x] wiki image update
- [ ] wiki [text update](https://github.com/ComputationalRadiationPhysics/picongpu/wiki/PIConGPU-domain-definitions#moving-window)
- [ ] wiki: add command order in one time step (calc, s+1, window check, plugins)

**Test:**

- [x] LWFA example
- [x] check offsets in HDF5 file after 1,760,000 steps (test was performed with a version befor the variable renaming)

g117

### CODE REVIEW

File: src/picongpu/include/simulationControl/MovingWindow.hpp [hunk 1]
```diff
@@ -51,45 +51,84 @@ class MovingWindow
...
+                subGrid.getGlobalDomain().size.y() - subGrid.getLocalDomain().size.y();
+
+            const uint32_t gpuLocalSizeY = subGrid.getLocalDomain().size.y();
+            const float_64 cellHeight = float_64(cellSize.y());
 
-            /* round to nearest cell to have smoother offset jumps */
-            if (offsetFirstGPU)
+            const float_64 deltaWayPerStep = (windowMovingSpeed * float_64(DELTA_T));
+
+            /* How many cells the virtual particle with speed of light is pushed forward
```
Comment (ax3l) [inline src/picongpu/include/simulationControl/MovingWindow.hpp]: This is a test memo.

Comment (psychocoderHPC) [inline src/picongpu/include/simulationControl/MovingWindow.hpp]: Test answer: 42

**Comment by psychocoderHPC** [comment]
I updated this branch that the slide point detection is more resistant against rounding errors.
Now support that the window speed can changed to over light speed in the future.

**Comment by ax3l** [comment]
@psychocoderHPC congrats on #1337, you are the king of leet! :crown:

File: src/picongpu/include/simulationControl/MovingWindow.hpp [hunk 2]
```diff
@@ -51,45 +51,90 @@ class MovingWindow
...
-                if (doSlide)
-                    *doSlide = true;
-            }
+            const SubGrid<simDim>& subGrid = Environment<simDim>::get().SubGrid();
+
+            /* speed of the moving window */
+            const float_64 windowMovingSpeed = float_64(SPEED_OF_LIGHT);
+
+            /* the moving window is smaller than the global domain by exactly one
+             * GPU (local domain size)
```
Comment (ax3l) [inline src/picongpu/include/simulationControl/MovingWindow.hpp]: add `\todo calculation of the globalWindowSizeY is constant should be only done once in it's own central object/api`

File: src/picongpu/include/simulationControl/MovingWindow.hpp [hunk 3]
```diff
@@ -51,45 +51,90 @@ class MovingWindow
...
+
+            /* Is the point when the virtual particle **passed** the GPU next to the last
+             * in the current step
+             */
+            const uint32_t firstSlideStep = math::floor(
+                float_64(subGrid.getGlobalDomain().size.y() - slidePointOffsetCells) * cellHeight / deltaWayPerStep
+            );
+
+            /* size of the moving window in pic length */
+            const float_64 windowRealSizeY = float_64(globalWindowSizeY - slidePointOffsetCells) * cellHeight;
```
Comment (ax3l) [inline src/picongpu/include/simulationControl/MovingWindow.hpp]: rename: `windowRealSizeY` (wrong naming)

File: src/picongpu/include/simulationControl/MovingWindow.hpp [hunk 4]
```diff
@@ -51,45 +51,90 @@ class MovingWindow
...
 
-            /* round to nearest cell to have smoother offset jumps */
-            if (offsetFirstGPU)
+            if (firstMoveStep <= currentStep)
             {
-                *offsetFirstGPU = math::floor(((float_64) stepsInLastGPU + stepsInFutureAfterComma) *
-                                              light_way_per_step / cell_height + 0.5);
+                /* calculate the current position of the virtual particle */
+                const float_64 currentVParticlePosition = deltaWayPerStep * float_64(currentStep);
+                const float_64 currentVParticleCell = currentVParticlePosition / cellHeight;
```
Comment (ax3l) [inline src/picongpu/include/simulationControl/MovingWindow.hpp]: `uint32_t(math::floor(` at this point

File: src/picongpu/include/simulationControl/MovingWindow.hpp [hunk 5]
```diff
@@ -51,45 +51,90 @@ class MovingWindow
...
+                const uint32_t virtualParticlePosition = uint32_t(math::floor(currentVParticleCell)) + slidePointOffsetCells;
+
+                /* calculate the position of the virtual particle after the current step is calculated */
+                const float_64 nextVParticlePosition = deltaWayPerStep * float_64(currentStep + 1);
+                const float_64 nextVParticleCell = nextVParticlePosition / cellHeight;
```
Comment (ax3l) [inline src/picongpu/include/simulationControl/MovingWindow.hpp]: same as above

File: src/picongpu/include/simulationControl/MovingWindow.hpp [hunk 6]
```diff
@@ -51,45 +51,90 @@ class MovingWindow
...
+            );
 
-            /* round to nearest cell to have smoother offset jumps */
-            if (offsetFirstGPU)
+            if (firstMoveStep <= currentStep)
             {
-                *offsetFirstGPU = math::floor(((float_64) stepsInLastGPU + stepsInFutureAfterComma) *
-                                              light_way_per_step / cell_height + 0.5);
+                /* calculate the current position of the virtual particle */
+                const float_64 currentVParticlePosition = deltaWayPerStep * float_64(currentStep);
```
Comment (ax3l) [inline src/picongpu/include/simulationControl/MovingWindow.hpp]: rename:
- `virtualParticleWayPassed`
- `virtualParticleWayPassedInCells`
- `virtualParticlePositionInCells`

File: src/picongpu/include/simulationControl/MovingWindow.hpp [hunk 7]
```diff
@@ -51,45 +51,90 @@ class MovingWindow
...
+            /* the moving window is smaller than the global domain by exactly one
+             * GPU (local domain size)
+             */
+            const uint32_t globalWindowSizeY =
+                subGrid.getGlobalDomain().size.y() - subGrid.getLocalDomain().size.y();
+
+            const uint32_t gpuLocalSizeY = subGrid.getLocalDomain().size.y();
+            const float_64 cellHeight = float_64(cellSize.y());
+
+            const float_64 deltaWayPerStep = (windowMovingSpeed * float_64(DELTA_T));
```
Comment (ax3l) [inline src/picongpu/include/simulationControl/MovingWindow.hpp]: wayPerStep

File: src/picongpu/include/simulationControl/MovingWindow.hpp [hunk 8]
```diff
@@ -51,45 +51,90 @@ class MovingWindow
...
             {
-                *offsetFirstGPU = math::floor(((float_64) stepsInLastGPU + stepsInFutureAfterComma) *
-                                              light_way_per_step / cell_height + 0.5);
+                /* calculate the current position of the virtual particle */
+                const float_64 currentVParticlePosition = deltaWayPerStep * float_64(currentStep);
+                const float_64 currentVParticleCell = currentVParticlePosition / cellHeight;
+                const uint32_t virtualParticlePosition = uint32_t(math::floor(currentVParticleCell)) + slidePointOffsetCells;
+
+                /* calculate the position of the virtual particle after the current step is calculated */
+                const float_64 nextVParticlePosition = deltaWayPerStep * float_64(currentStep + 1);
```
Comment (ax3l) [inline src/picongpu/include/simulationControl/MovingWindow.hpp]: rename:
- `float_64 nextVirtualParticleWayPassed`
- `uint32_t nextVirtualParticleWayPassedInCells`
- `uint32_t nextVirtualParticlePositionInCells`

File: src/picongpu/include/simulationControl/MovingWindow.hpp [hunk 9]
```diff
@@ -51,45 +51,90 @@ class MovingWindow
...
+                const float_64 nextVParticleCell = nextVParticlePosition / cellHeight;
+                /* This position is used to detect the point in time where the virtual particle
+                 * moves over a GPU border.
+                 */
+                const uint32_t virtualParticleNextPosition =  uint32_t(math::floor(nextVParticleCell)) + slidePointOffsetCells;
+
+                /* Moving window start moving if the virtual particle passed the border of
```
Comment (ax3l) [inline src/picongpu/include/simulationControl/MovingWindow.hpp]: below this part of the member we are checking if our *move* does cause a *slide*
-> fix comment to something like

```
slide handling starts here ...
```

File: src/picongpu/include/simulationControl/MovingWindow.hpp [hunk 10]
```diff
@@ -51,45 +51,90 @@ class MovingWindow
...
+                 * between two GPUs in the current step.
+                 * We slide if the virtual particle is in the next step on another GPU than in
+                 * the current step but not before the first slide step.
+                 */
+                if (firstSlideStep <= currentStep &&
```
Comment (ax3l) [inline src/picongpu/include/simulationControl/MovingWindow.hpp]: maybe `currentStep >= firstSlideStep`

Comment (ax3l) [inline src/picongpu/include/simulationControl/MovingWindow.hpp]: let us put this in it's own vars, for more comment fun

```C++
// within the current (to be calculated) time step the virtual particle will have reached
// at least the position of the cell behind the end of the initial global domain
// (also true for all later time steps)
const bool endOfInitialGlobalDomain = firstSlideStep <= currentStep;

// virtual particle will pass a GPU border during the current (to be calculated) time step
const bool virtualParticlePassesGPUBorder =
    (virtualParticleNextPosition % gpuLocalSizeY) <
    (virtualParticlePosition % gpuLocalSizeY);

if( endOfInitialGlobalDomain && virtualParticlePassesGPUBorder )
{
    // ...
}
```

File: src/picongpu/include/simulationControl/MovingWindow.hpp [hunk 11]
```diff
@@ -51,45 +51,90 @@ class MovingWindow
...
+                        *doSlide = true;
+                }
+
+                /* valid range for the offset is [0;GPU size in y direction) */
+                if (offsetFirstGPU)
+                {
+                    /* virtualParticleNextPosition is used because
+                     * `virtualParticlePosition % gpuLocalSizeY` == gpuLocalSizeY - 1
+                     * in the step where the slide is done
+                     */
```
Comment (ax3l) [inline src/picongpu/include/simulationControl/MovingWindow.hpp]: add `note: also works with windowMovingSpeed > c`

File: src/picongpu/include/simulationControl/MovingWindow.hpp [hunk 12]
```diff
@@ -51,45 +51,90 @@ class MovingWindow
...
+                if (firstSlideStep <= currentStep &&
+                   (virtualParticleNextPosition % gpuLocalSizeY) < (virtualParticlePosition % gpuLocalSizeY)
+                )
+                {
+                    incrementSlideCounter(currentStep);
+                    if (doSlide)
+                        *doSlide = true;
+                }
+
+                /* valid range for the offset is [0;GPU size in y direction) */
```
Comment (ax3l) [inline src/picongpu/include/simulationControl/MovingWindow.hpp]: add:
`since the moving window in PIConGPU always starts on the first plane (3D) / row (2D) of GPUs in y direction, this
is calculation is equal to the globalWindow.offset in y`

**Comment by psychocoderHPC** [comment]
ready for review

**Comment by ax3l** [comment]
we updated the [wiki images](https://github.com/ComputationalRadiationPhysics/picongpu/wiki/PIConGPU-domain-definitions#moving-window) but we should also give the text an update with this PR.

**Comment by psychocoderHPC** [comment]
| step | cell offset pull | cell offset dev |
|---|---|---|
| 10,000  | 9004 | 9009  |   
| 690,000  | 648652  | 649009  |   
| 1,240,000  | 1166013  | 1166656  |   
| 1,760,000  | 1655156  | 1656067  |  

```
window moving speed dev:  2.999575e8
window moving speed pull: 2.997925e8
reference speed:          2.997925e8
```

**Comment by psychocoderHPC** [comment]
I updated the picture of this pull request

**Comment by ax3l** [comment]
pls update the wiki picture (add the svg to `wiki.git`) :)

I merge for now, great work! :sparkles:
