### PR TITLE
[breaking change] fix openPMD particles `positionOffset`

### LINKED ISSUE #4276: openPMD-api output: global window offset only in meshes
Apparently, the [*global window offset*](https://github.com/ComputationalRadiationPhysics/picongpu/wiki/PIConGPU-domain-definitions) of a simulation is only stored in mashes with PIConGPU's openPMD-api output. 
This is fine as long as both meshes and fields are stored, but highly unpractical if one has only particle data and needs to determine the lab-frame position of particles, which requires the *global window offset* + the *position offset* + the *(in cell) position* to be added. 
Previously, PIConGPU stored a *position offset* with the *global window offset* added to it - but this seems to to be the case anymore. 

I am not sure whether this issue is caused by PIConGPU or the [openPMD-api](https://github.com/openPMD/openPMD-api) standard and whether there is a standard-conform way of solving this. 

Thanks to @nicowrobel for finding this issue.

### PR DESCRIPTION
**Pull request by psychocoderHPC**
fix #4276

PIConGPU used offsets relative to the data domain (global domain) instead of total offsets for particles. This aviods performing particle analysis if there are no field data because there was no way to get the total particle position.

**This PR is a breaking change, post-processing tools must be updated, and restarting from checkpoints (IO file version 0.1) created before this PR is no longer possible.**

- [x] rebase against #4287 and introduce a new major file version

### CODE REVIEW

File: include/picongpu/plugins/openPMD/openPMDWriter.hpp [hunk 1]
```diff
@@ -1409,10 +1409,22 @@ make sure that environment variable OPENPMD_BP_BACKEND is not set to ADIOS1.
 
             void write(ThreadParams* threadParams, std::string mpiTransportParams)
             {
+                const SubGrid<simDim>& subGrid = Environment<simDim>::get().SubGrid();
                 /* y direction can be negative for first gpu */
```
Comment (sbastrakov) [inline include/picongpu/plugins/openPMD/openPMDWriter.hpp]: Is this comment needed? I think in the new code it's already expressed in line 1420

**Review by sbastrakov — COMMENTED** [review]
Other then a note above seems good. Though this change seems quite difficult to check only with one's eyes. How did you test it?

File: include/picongpu/plugins/openPMD/openPMDWriter.hpp (hunk 1 above)
Comment (psychocoderHPC) [reply include/picongpu/plugins/openPMD/openPMDWriter.hpp]: Yes  I will remove the comment.

**Comment by sbastrakov** [comment]
@psychocoderHPC can be rebased now

**Comment by psychocoderHPC** [comment]
I rebased this PR and increased the IO file version from 0.1 to 1.0 (see https://github.com/ComputationalRadiationPhysics/picongpu/pull/4287). This will disallow restarting from old checkpoint files.

**Review by sbastrakov — APPROVED** [review]

File: include/picongpu/plugins/openPMD/openPMDWriter.hpp [hunk 2]
```diff
@@ -1482,10 +1482,21 @@ make sure that environment variable OPENPMD_BP_BACKEND is not set to ADIOS1.
...
-                const pmacc::Selection<simDim> localDomain = Environment<simDim>::get().SubGrid().getLocalDomain();
-                DataSpace<simDim> particleOffset(localDomain.offset);
-                particleOffset -= threadParams->window.globalDimensions.offset;
+                const SubGrid<simDim>& subGrid = Environment<simDim>::get().SubGrid();
+                const pmacc::Selection<simDim> localDomain = subGrid.getLocalDomain();
+                /* Offset to transform local particle offsets into total offsets for all particles within the
+                 * current window.
+                 * @attention A window can be the full simulation domain or the moving window.
+                 */
+                DataSpace<simDim> windowCellOffsetToTotalDomain(localDomain.offset);
```
Comment (psychocoderHPC) [inline include/picongpu/plugins/openPMD/openPMDWriter.hpp:1491]: Maybe a bug: Most likely this must be `DataSpace<simDim> windowCellOffsetToTotalDomain(localDomain.offset+subGrid.getGlobalDomain().offset);`

File: include/picongpu/plugins/openPMD/restart/LoadSpecies.hpp [hunk 3]
```diff
@@ -206,15 +208,19 @@ namespace picongpu
...
 
-                // Note: the global domain offset is already included in params->window.globalDimensions.offset
-                DataSpace<simDim> const patchOffset
-                    = params->window.globalDimensions.offset + params->window.localDimensions.offset;
+                const SubGrid<simDim>& subGrid = Environment<simDim>::get().SubGrid();
+                auto globalDOmainOffset = subGrid.getGlobalDomain().offset;
+                /* window.localDimensions.offset is in PIConGPU for a restart zero but to stay generic we take
+                 * the variable into account.
+                 */
+                DataSpace<simDim> const patchTotalOffset = globalDOmainOffset + params->window.globalDimensions.offset
```
Comment (psychocoderHPC) [inline include/picongpu/plugins/openPMD/restart/LoadSpecies.hpp:216]: Maybe must be `DataSpace<simDim> const patchTotalOffset = globalDOmainOffset + subGrid.getLocalDomain()`

File: include/picongpu/plugins/openPMD/openPMDWriter.hpp (hunk 2 above)
Comment (PrometheusPi) [reply include/picongpu/plugins/openPMD/openPMDWriter.hpp:1491]: @psychocoderHPC I will test this.

Comment (PrometheusPi) [reply include/picongpu/plugins/openPMD/openPMDWriter.hpp:1491]: Checked - does not fix the problem (simulation: default LaserWakefield example `8.cfg`) 
For details on the plot, please see #4319
grafik

Comment (PrometheusPi) [reply include/picongpu/plugins/openPMD/openPMDWriter.hpp:1491]: Full result looks as 
grafik

Thus is got actually worse than before.

Comment (PrometheusPi) [reply include/picongpu/plugins/openPMD/openPMDWriter.hpp:1491]: @psychocoderHPC I was looking at the definition here: https://github.com/ComputationalRadiationPhysics/picongpu/wiki/PIConGPU-domain-definitions . Is it still valid? 

If yes, what is with the `globalWindow.offset`?

Comment (psychocoderHPC) [reply include/picongpu/plugins/openPMD/openPMDWriter.hpp:1491]: @PrometheusPi Yes the plot is still valid. I do not understand what you mean with `globalWindow.offset`?

Comment (PrometheusPi) [reply include/picongpu/plugins/openPMD/openPMDWriter.hpp:1491]: @psychocoderHPC What I meant was that I thought we compute the offset of the window (shaded area) and thus need `globalWindow.offset` (underlined in red below). 
But now I think what you calculate is the global position of one of the blue cells by adding the values `globalDomain.offset` and `localDomain.offset` (circled in red). 
grafik

Is the "Window" not the output window we use for openPMD output?
