### PR TITLE
Fix #702 Activate new plugins after restart

### LINKED ISSUE #702: crash - add plugin after restart
@BeyondEspresso just informed me that some plugins crash if they are activated after a restart.
E.g. if the `binEnergy` plugin is not called via the command line flag `picongpu ... --bin_e.period 100 ...`, before the restart, but after the restart the plugin is called, the plugin tries to read previous data files, which do not exist, and crashes.

The following plugins are affected:
 - BinEnergyParticles
 - CountParticles
 - EnergyFields
 - EnergyParticles

EDIT: All plugins using `restoreTxtFile` defined in `txtFileHandling.hpp` are affected.

### PR DESCRIPTION
**Pull request by PrometheusPi**
This pull request solves issue #702:
If we add plugin calls via command line after a restart, checkpoint files for the plugin do not exists thus crashing PIConGPU during the attempt to copy checkpoint files to output files.
This pull request now checks whether a checkpoint file exists. If it does, everthing is handled as before. If the required checkpoint file does not exist, a warning is printed and we just start with data output from the restart point. PIConGPU does not crash anymore.

**To Do:**
- [x] verify that this pull request solves the restart crash 
- [x] verify that standard restart still works

### CODE REVIEW

**Comment by ax3l** [comment]
huh, good catch. I missed that case while implementing it.

File: src/picongpu/include/plugins/common/txtFileHandling.hpp [hunk 1]
```diff
@@ -46,28 +47,46 @@ using namespace boost::filesystem;
...
         path dst( filename );
 
-        copy_file( src,
-                   dst,
-                   copy_option::overwrite_if_exists );
-
-        outFile.open( filename.c_str(), std::ofstream::out | std::ostream::app );
-        if( !outFile )
+        /* check whether restart file exists */
+        std::ifstream restartFile(src.c_str());
```
Comment (ax3l) [inline src/picongpu/include/plugins/common/txtFileHandling.hpp]: That's an interesting way of checking that.
We usually use `if (!boost::filesystem::exists(src))` for that - maybe that's more suited here, too.

File: src/picongpu/include/plugins/common/txtFileHandling.hpp [hunk 2]
```diff
@@ -46,28 +47,46 @@ using namespace boost::filesystem;
...
+        if(! restartFile.good())
         {
-            std::cerr << "[Plugin] Can't open file '" << filename
-                      << "', output disabled" << std::endl;
-            return false;
+            /* restart file does not exists */
+            restartFile.close();
+            std::cerr << "Plugin restart file: \n \t" << src << "\n was not found." << std::endl;
```
Comment (ax3l) [inline src/picongpu/include/plugins/common/txtFileHandling.hpp]: I think that is not ideal for "cerr" but could be maybe better in a log level such as `INPUT_OUTPUT`.

File: src/picongpu/include/plugins/common/txtFileHandling.hpp [hunk 3]
```diff
@@ -46,28 +47,46 @@ using namespace boost::filesystem;
...
+                outFile.close();
+
+            copy_file( src,
+                       dst,
+                       copy_option::overwrite_if_exists );
+
+            outFile.open( filename.c_str(), std::ofstream::out | std::ostream::app );
+            if( !outFile )
+            {
+                std::cerr << "[Plugin] Can't open file '" << filename
```
Comment (ax3l) [inline src/picongpu/include/plugins/common/txtFileHandling.hpp]: this line on the other hand is an *unexpected* state. even if log `INPUT_OUTPUT` would apply somehow, I think `cerr` is appropriate.

**Comment by ax3l** [comment]
great fix! :+1:

File: src/picongpu/include/plugins/common/txtFileHandling.hpp (hunk 1 above)
Comment (PrometheusPi) [inline src/picongpu/include/plugins/common/txtFileHandling.hpp]: @ax3l Thanks, that's way better. I will change it to `boost::filesystem::...`.

File: src/picongpu/include/plugins/common/txtFileHandling.hpp (hunk 2 above)
Comment (PrometheusPi) [inline src/picongpu/include/plugins/common/txtFileHandling.hpp]: I will change this to a log warning.

File: src/picongpu/include/plugins/common/txtFileHandling.hpp (hunk 3 above)
Comment (PrometheusPi) [inline src/picongpu/include/plugins/common/txtFileHandling.hpp]: I will keeps this a `std::cerr`.

Comment (ax3l) [inline src/picongpu/include/plugins/common/txtFileHandling.hpp]: :+1:

File: src/picongpu/include/plugins/common/txtFileHandling.hpp [hunk 4]
```diff
@@ -46,28 +47,44 @@ using namespace boost::filesystem;
...
-        outFile.open( filename.c_str(), std::ofstream::out | std::ostream::app );
-        if( !outFile )
+        /* check whether restart file exists */
+        if( !boost::filesystem::exists( src ) )
         {
-            std::cerr << "[Plugin] Can't open file '" << filename
-                      << "', output disabled" << std::endl;
-            return false;
+            /* restart file does not exists */
+            log<picLog::INPUT_OUTPUT> ("Plugin restart file:");
```
Comment (ax3l) [inline src/picongpu/include/plugins/common/txtFileHandling.hpp]: oh, please keep it a one-liner. else it's a huge mess in parallel outputs.

File: src/picongpu/include/plugins/common/txtFileHandling.hpp [hunk 5]
```diff
@@ -46,28 +47,44 @@ using namespace boost::filesystem;
...
+            log<picLog::INPUT_OUTPUT> ("\t %1%") % src ;
```
Comment (ax3l) [inline src/picongpu/include/plugins/common/txtFileHandling.hpp]: (we usually do not use tabs for that ;) )
