### PR TITLE
Fix treatment of bool particle attributes in openPMD plugin

### LINKED ISSUE #3732: Execution of 'new' PIConGPU with openPMD fails with `unknown datatype (switchType)`
I have attempted to run a simulation with newest (baf0da494bd4d7e432033dd61242f4efcba1d39d) PIC and openPMD 0.14.1, 0.14.2/dev (040a9b0) on JWB and hemera - to no avail.

The simulations will consistently fail on the first attempt to write data with openPMD. The errors are identical, whether I try to write particle & field data or a checkpoint.

Excerpts from `stderr` for the above commit of PIC:
`Unhandled exception of type 'St13runtime_error' with message 'Internal error: Encountered unknown datatype (switchType) ->35', terminating`
```
[cupla] Error: </p/project/pwfaradiation/lebedev1/PIConGPU_SourcesAndLibs_Aug21/picongpu-dev/include/pmacc/../pmacc/memory/buffers/HostBufferIntern.hpp>:71 
[cupla] Error: </p/project/pwfaradiation/lebedev1/PIConGPU_SourcesAndLibs_Aug21/picongpu-dev/include/pmacc/../pmacc/memory/buffers/Buffer.hpp>:69
```

```
[cupla] Error: </p/project/pwfaradiation/lebedev1/PIConGPU_SourcesAndLibs_Aug21/picongpu-dev/include/pmacc/../pmacc/me
mory/buffers/Buffer.hpp>:69 
 6 0x0000000000e9f768 _ZThn56_N8picongpu9ParticlesIN5pmacc4meta6StringIJLc119ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0E
Lc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0ELc0EEEEN5boost3mpl6v_itemINS_11chargeRatioINS_20ChargeRatioElectronsENS1_13pmacc_isAliasEEENS7_INS_9massRatioINS_18MassRatioElectronsESA_EENS7_INS_12densityRatioINS_17DensityRatioBunchESA_EENS7_INS_7currentINS_13currentSolver3EmZINS_9particles6shapes3TSCENSJ_8strategy16CachedSupercellsEEESA_EENS7_INS_13interpolationINS_28FieldToParticleInterpolationISN_NS_30AssignedTrilinearInterpolationEEESA_EENS7_INS_5shapeISN_SA_EENS7_INS_14particlePusherINSL_6pusher9CompositeINS10_12AccelerationENS10_5BorisENS10_38CompositeBinarySwitchActivationFunctorILj22838EEEEESA_EENS6_7vector0IN4mpl_2naEEELi0EEELi0EEELi0EEELi0EEELi0EEELi0EEELi0EEENS7_INS_13radiationMaskENS7_INS_13momentumPrev1ENS7_INS_9weightingENS7_INS_8momentumENS7_INS_8positionINS_12position_picESA_EES1B_Li0EEELi0EEELi0EEELi0EEELi0EEEED0Ev()  ???:0
```

My guess _was_ that the problem lies with the `CompositeBinarySwitchActivationFunctor`, i.e., the functor that allows me to 
switch from acceleration to actual propagation w/o checkpointing first. However, removing said functor from `species.param` and `particle.param` did **not** solve the issue.

These - or largely similar - errors have also been observed on hemera.

Library configurations and config/cmake outputs are attached. 
[LibConfig.md](https://github.com/ComputationalRadiationPhysics/picongpu/files/7026201/LibConfig.md)

### PR DESCRIPTION
**Pull request by sbastrakov**
ADIOS2 backend does not support bools which caused exceptions.
Redefine `GetComponentsType` trait to treat bools as chars.

Fixes #3732

@Anton-Le I checked that this version compiles, writes checkpoints, and restarts from them on our dev machine. I had no easy way to check if the read values are correct. Could you check it? In case you use some older PIConGPU, should be no problem, could apply the same changes.

### CODE REVIEW

File: include/picongpu/plugins/openPMD/GetComponentsType.hpp [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+        /** Get component type trait for bools in openPMD output
+         *
+         * ADIOS2 backend of openPMD API currently does not support bool datasets #3732.
+         * So with this specialization, PIConGPU particle attributes of type bool (e.g. radiationMask,
+         * transitionRadiationMask) are treated as chars.
+         *
+         * This requires sizeof(bool) == sizeof(char), ::type is defined only in this case.
+         */
+        template<>
+        struct GetComponentsType<bool>
```
Comment (franzpoeschel) [inline include/picongpu/plugins/openPMD/GetComponentsType.hpp:41]: Could you maybe add a little comment which file contains the original definition of `GetComponentsType` (`pmacc/traits/GetComponentsType.hpp`)? It's was not immediately obvious to me that this "overrides" a definition found somewhere completely different.

Comment (sbastrakov) [reply include/picongpu/plugins/openPMD/GetComponentsType.hpp:41]: In this case it's actually the "standard" location that corresponds to the namespace structure. But sure, I can add a sentence about it.

Comment (sbastrakov) [reply include/picongpu/plugins/openPMD/GetComponentsType.hpp:44]: Done

**Review by psychocoderHPC — APPROVED** [review]

**Comment by sbastrakov** [comment]
I could not reproduce the issue with restarting yet. I think having this PR merged should fix at least some, and not introduce any new problems.
