### PR TITLE
close #882 - fix gas free formular

### LINKED ISSUE #882: Position (Offset) in GasFreeFormula
The `GasFreeFormula` should provide a simple interface `f(\vec x)` where `x` is a position or offset (in normalized length) as it is in the current [master](https://github.com/ComputationalRadiationPhysics/picongpu/blob/ac82b4c96d5659380042b0e61f14092961e36120/src/picongpu/include/simulation_defines/param/gasConfig.param#L208).

Currently, a [cellOffset](https://github.com/ComputationalRadiationPhysics/picongpu/blob/e394fb1394ae186bde7d256a97578e3ec17e3207/src/picongpu/include/simulation_defines/param/gasConfig.param#L253) is used in `dev`. It is also not correctly converted to a `length` again since that would require a multiplication with the *normalized* cellSize and only in *addition* a multiplication with `unitLength` to get SI again.

We should therefore refactor the interface (multiply with cellSize beforehand) or update the examples since they are currently calculating the global position of the cell wrong.

### PR DESCRIPTION
**Pull request by PrometheusPi**
This pull request solves issue #882:
It changes to interface from gasFreeFormular from *cell offset* back to *position in SI units*.

**No examples** are affected by this pull request.

`gasConfig.param` was changed for the reference file.

### CODE REVIEW

**Comment by ax3l** [comment]
great pull, thx!

is it possible to access `cellSize` inside the kernels? It might be necessary to calculate an offset in cells, e.g., for debugs or to load image/hdf5 data.

**Comment by PrometheusPi** [comment]
@ax3l no problem. @psychocoderHPC already asked for that too (in person). I will give make both available:
 - length in SI units
 - and cell position
even if they are related

**Comment by PrometheusPi** [comment]
@ax3l I made `cellSize` available in the functor, so that one can compute the cell position.

File: src/picongpu/include/particles/gasProfiles/FreeFormulaImpl.hpp [hunk 1]
```diff
@@ -51,9 +51,11 @@ struct FreeFormulaImpl : public T_ParamClass
      */
     HDINLINE float_X operator()(const DataSpace<simDim>& totalCellOffset)
     {
-        const float_64 unit_length = UNIT_LENGTH;
+        DataSpace<simDim> position_SI = totalCellOffset;
+        for(unsigned int i = 0; i<simDim ; i++)
+            position_SI[i] *= cellSize[i] * UNIT_LENGTH;
 
-        float_X density = ParamClass::operator()( totalCellOffset, unit_length );
+        float_X density = ParamClass::operator()( position_SI , cellSize );
```
Comment (psychocoderHPC) [inline src/picongpu/include/particles/gasProfiles/FreeFormulaImpl.hpp]: `cellSize` is in `PIConGPU` units not in `SI` this might be confuse the user

**Comment by PrometheusPi** [comment]
@psychocoderHPC thanks for pointing this out - I fixed it.

**Comment by PrometheusPi** [comment]
@ax3l?

File: src/picongpu/include/particles/gasProfiles/FreeFormulaImpl.hpp [hunk 2]
```diff
@@ -51,9 +51,15 @@ struct FreeFormulaImpl : public T_ParamClass
...
+        DataSpace<simDim> position_SI = totalCellOffset;
+        cellSize_t cellSize_SI = cellSize;
+        for(unsigned int i = 0; i<simDim ; i++)
+        {
+            cellSize_SI *= UNIT_LENGTH;
+            position_SI[i] *= cellSize_SI[i];
+        }
 
-        float_X density = ParamClass::operator()( totalCellOffset, unit_length );
+        float_X density = ParamClass::operator()( position_SI , cellSize_SI );
```
Comment (ax3l) [inline src/picongpu/include/particles/gasProfiles/FreeFormulaImpl.hpp]: pedantic: no space before `,`

File: src/picongpu/include/simulation_defines/param/gasConfig.param [hunk 3]
```diff
@@ -242,29 +242,34 @@ struct FreeFormulaFunctor
...
     {
-        const float_64 y = float_64(totalCellOffset.y()) * unitLength * 1000.0; // m -> mm
+        const float_64 y = float_64(position_SI.y()) * 1000.0; // m -> mm
+        //const unsigned int y_cell_id = position_SI.y() / cellSize_SI[1];
 
         /* triangle function example
          * for a density profile from 0 to 400 microns */
         float_64 s = 1.0 - 5.0 * math::abs(y - 0.2);
 
+        /* give it an on/off shape for everey second cell */
```
Comment (ax3l) [inline src/picongpu/include/simulation_defines/param/gasConfig.param]: every

**Comment by ax3l** [comment]
@PrometheusPi very well done, thank you a bunch!

**Comment by PrometheusPi** [comment]
fixed your typos (and rebased against dev - that's why all comits are reordered now)

**Comment by ax3l** [comment]
very well done, thank you!

**Comment by ax3l** [comment]
I am not sure why I merged this, I am just spotting a few bugs ;) (will put them inline)

File: src/picongpu/include/particles/gasProfiles/FreeFormulaImpl.hpp [hunk 4]
```diff
@@ -51,9 +51,15 @@ struct FreeFormulaImpl : public T_ParamClass
      */
     HDINLINE float_X operator()(const DataSpace<simDim>& totalCellOffset)
     {
-        const float_64 unit_length = UNIT_LENGTH;
+        DataSpace<simDim> position_SI = totalCellOffset;
+        cellSize_t cellSize_SI = cellSize;
+        for(unsigned int i = 0; i<simDim ; i++)
+        {
+            cellSize_SI *= UNIT_LENGTH;
```
Comment (ax3l) [inline src/picongpu/include/particles/gasProfiles/FreeFormulaImpl.hpp]: `cellSize_t` is of type [float_X](https://github.com/ComputationalRadiationPhysics/picongpu/blob/4c6c28c1b349abdda5b7e4178071d4a9c5aeab86/src/picongpu/include/simulation_defines/unitless/gridConfig.unitless#L35) and does not guarantee to hold a SI-scaled value.

**Comment by PrometheusPi** [comment]
I will take care of them.

File: src/picongpu/include/particles/gasProfiles/FreeFormulaImpl.hpp [hunk 5]
```diff
@@ -51,9 +51,15 @@ struct FreeFormulaImpl : public T_ParamClass
...
+            position_SI[i] *= cellSize_SI[i];
```
Comment (ax3l) [inline src/picongpu/include/particles/gasProfiles/FreeFormulaImpl.hpp]: each component of `position_SI` is, as the [DataSpace](https://github.com/ComputationalRadiationPhysics/picongpu/blob/4c6c28c1b349abdda5b7e4178071d4a9c5aeab86/src/libPMacc/include/dimensions/DataSpace.hpp#L41) components, of type `int` which will not behave well when scaled to `meters`.

**Comment by ax3l** [comment]
I already prepared a pull, don't worry.

**Comment by PrometheusPi** [comment]
great
