### PR TITLE
fix adios 1.11.0 compile

### LINKED ISSUE #1650: adios 1.11.0 broken
PIConGPU with  with adios 1.11.0 enabled does not compile.

Error:
```
/home/buildbot/picongpu-src/src/picongpu/include/plugins/adios/ADIOSWriter.hpp(965): error: identifier "adios_stat_no" is undefined
```

The interface of
```C++
int adios_declare_group ( int64_t * id ,
const char * name ,
const char * time_index ,
enum ADIOS_FLAG stats )
```
is changed to 

```C++
int adios_declare_group ( int64_t * id ,
const char * name ,
const char * time_index ,
enum ADIOS_STATISTICS_FLAG stats )
```

~~This bug is triggered the first time by our compile suite inside the issue #1645.~~ [update:] compile suite used adios 1.10.0 the error in #1645 is triggered by a wrong change

### PR DESCRIPTION
**Pull request by psychocoderHPC**
remove `adios_flag_no` with integer value `2`

The interface of `adios_declare_group` is changed in adios version 1.11.0, see #1650

close #1650

### CODE REVIEW

File: src/picongpu/include/plugins/adios/ADIOSWriter.hpp [hunk 1]
```diff
@@ -961,11 +961,21 @@ class ADIOSWriter : public ILightweightPlugin
         DataSpace<simDim> particleOffset(localDomain.offset);
         particleOffset.y() -= threadParams->window.globalDimensions.offset.y();
 
+        /* The interface of `adios_declare_group()` is changed from adios 1.10.0 to 1.11.0.
+         *
+         * Before 1.11.0 we need to use the enum `ADIOS_FLAG` else `ADIOS_STATISTICS_FLAG`
```
Comment (ax3l) [inline src/picongpu/include/plugins/adios/ADIOSWriter.hpp]: shorter and more precise:
```C++
/* ADIOS API change:
 * <= 1.10.0: `enum ADIOS_FLAG`
 * >= 1.11.0: `enum ADIOS_STATISTICS_FLAG`
 */
```

**Comment by ax3l** [comment]
thx for the quick fix! I would just condense the inline comment a bit more to the point

**Comment by ax3l** [comment]
note (out of scope of this PR): generally, we should expose that option to the user similar to the transform

**Comment by ax3l** [comment]
thx for the fix! :)
